version: '3'

services: 

    backend:
        build:
            context: .
            dockerfile: ./django/Dockerfile
        restart: always
        command: >
            /bin/bash -c "pip install -r /require/requirements.txt && python manage.py runserver 0.0.0.0:80"
        networks: 
            - default
        volumes: 
            - ./backend/:/app
            - ./backend/requirements.txt:/require/requirements.txt
        depends_on:
            - mysql

        ports:
            - ${BACKEND_PORT}:80

    frontend:
        image: node:14-alpine
        command: >
            /bin/sh -c "yarn && yarn dev"
        working_dir: /app
        networks: 
            - default
        depends_on: 
            - mysql
        volumes: 
            - ./frontend:/app
        ports:
            - ${FRONTEND_PORT}:3000


    mysql:
        image: mysql:5.7
        environment: 
            MYSQL_DATABASE: ${DATABASE_DBNAME}
            MYSQL_USER: ${DATABASE_USER}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
        networks: 
            - default
        volumes: 
            - medstore-workshop-db:/var/lib/mysql
            - ./mysql/config/my.cnf:/etc/mysql/my.cnf
    
    pma:
        image: phpmyadmin/phpmyadmin
        networks:
            - default
        environment: 
            PMA_HOST: mysql
            PMA_PORT: 3306
        ports:
            - ${PMA_PORT}:80
        depends_on: 
            - mysql

volumes: 
    medstore-workshop-db: